"""empty message

Revision ID: 102767f6765c
Revises: 3503d4cd5acf
Create Date: 2017-05-17 00:17:19.241369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102767f6765c'
down_revision = '3503d4cd5acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prob_answers', sa.Column('doctor_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prob_answers', 'doctor_id')
    # ### end Alembic commands ###
