"""empty message

Revision ID: 3503d4cd5acf
Revises: 53a60125db67
Create Date: 2017-05-12 19:11:19.018913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3503d4cd5acf'
down_revision = '53a60125db67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ques_answers', 'ip')
    op.drop_column('questionnaires', 'is_ban')
    op.drop_column('releases', 'start_time')
    op.drop_column('releases', 'security')
    op.drop_column('releases', 'end_time')
    op.drop_column('releases', 'is_closed')
    op.add_column('users', sa.Column('allow_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('days_before_email', sa.Integer(), nullable=True))
    op.drop_column('users', 'last_log_in')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_log_in', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'days_before_email')
    op.drop_column('users', 'allow_email')
    op.add_column('releases', sa.Column('is_closed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('releases', sa.Column('end_time', mysql.DATETIME(), nullable=True))
    op.add_column('releases', sa.Column('security', sa.BLOB(), nullable=True))
    op.add_column('releases', sa.Column('start_time', mysql.DATETIME(), nullable=True))
    op.add_column('questionnaires', sa.Column('is_ban', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('ques_answers', sa.Column('ip', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
