"""empty message

Revision ID: 3937a5ceaa86
Revises: d04ce12b705b
Create Date: 2017-05-17 15:16:45.783744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3937a5ceaa86'
down_revision = 'd04ce12b705b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
