"""empty message

Revision ID: 53a60125db67
Revises: 544c7e9b9222
Create Date: 2017-04-22 01:24:20.559794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a60125db67'
down_revision = '544c7e9b9222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('schema', sa.PickleType(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('is_ban', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ques_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ques_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ques_id'], ['questionnaires.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ques_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('security', sa.PickleType(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ques_id'], ['questionnaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prob_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ques_ans_id', sa.Integer(), nullable=True),
    sa.Column('prob_id', sa.Integer(), nullable=True),
    sa.Column('ans', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ques_ans_id'], ['ques_answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prob_answers')
    op.drop_table('releases')
    op.drop_table('ques_answers')
    op.drop_table('questionnaires')
    # ### end Alembic commands ###
