"""empty message

Revision ID: 64d5bbcff24d
Revises: ec1687bf15dc
Create Date: 2017-05-17 19:41:58.504092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64d5bbcff24d'
down_revision = 'ec1687bf15dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
